prometheus:
  # -- Create prometheus-operator resources
  enabled: true
  rule:
    # -- Optional Namespace for PrometheusRule resource
    namespace: ""
    # -- Additional Labels for PrometheusRule resource
    additionalLabels: {}
    alerts:
      # -- Enable CiliumErrorsAndWarning alert
      errorsAndWarning: true
    additionalAlerts: []
    # - alert: ReadyStatus
    #   annotations:
    #     description: 'App is not ready.'
    #     summary: App is not ready.
    #   expr: ready_status{condition="False"} == 1
    #   labels:
    #     severity: critical

grafana:
  # -- Enable deploying cert-manager dashboard to Grafana
  enabled: false
  # -- Add `grafana_dashboard: "1"` default label
  defaultLabel: true
  # -- Extra labels for dashboard ConfigMap
  extraLabels: {}
  # -- Extra annotations for dashboard ConfigMap
  extraAnnotations: {}
