# Default values for testing-multitool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: someblackmagic/k8s-testing-multitool
  tag: v0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
