{{- if and $.Values.prometheus.enabled ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )  }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "redis-monitoring.fullname" . }}
  {{- if $.Values.prometheus.rule.namespace }}
  namespace: {{ $.Values.prometheus.rule.namespace }}
  {{- end }}
  labels:
    {{- include "redis-monitoring.labels" . | nindent 4 }}
    {{- if $.Values.prometheus.rule.additionalLabels }}
    {{- toYaml $.Values.prometheus.rule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: redis
    rules:
    {{- if $.Values.prometheus.rule.alerts.down.enabled }}
    - alert: RedisDown
      expr: redis_up{service="{{ template "common.names.fullname" . }}-metrics"} == 0
      for: 2m
      annotations:
        description: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} is down`}}
        summary: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} down`}}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.down.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.memoryHigh.enabled }}
    - alert: RedisMemoryHigh
      expr: >
        redis_memory_used_bytes{service="{{ template "common.names.fullname" . }}-metrics"} * 100
        /
        redis_memory_max_bytes{service="{{ template "common.names.fullname" . }}-metrics"}
        > 90
      for: 5m
      annotations:
        summary: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} is using too much memory`}}
        description: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.`}}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.memoryHigh.severity }}"
    {{- end }}

    {{- if $.Values.prometheus.rule.alerts.keyEviction.enabled }}
    - alert: RedisKeyEviction
      expr: |
        increase(redis_evicted_keys_total{service="{{ template "common.names.fullname" . }}-metrics"}[5m]) > 0
      for: 1s
      annotations:
        summary: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} has evicted keys`}}
        description: {{`Redis&trade; instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.`}}
      labels:
        severity: "{{ $.Values.prometheus.rule.alerts.keyEviction.severity }}"
    {{- end }}

    {{- with $.Values.prometheus.rule.additionalAlerts }}
    {{ . | nindent 4 }}
    {{- end }}
{{- end }}
