apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}
    labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: ClusterIP
    ports:
        - port: 8125
          targetPort: 8125
          protocol: UDP
          name: statsd-udp
    selector:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
