apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "testing-multitool.fullname" . }}
  labels:
    app: {{ include "testing-multitool.name" . }}
    chart: {{ include "testing-multitool.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  {{- if .Values.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "testing-multitool.name" . }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "testing-multitool.name" . }}
        release: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
            - sleep
            - infinity
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash","-c","/bin/sleep 1; kill -QUIT 1" ]
    {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
