{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: {{ $.Values.serviceMonitor.namespace | default $.Release.Namespace }}
  labels:
    {{- include "longhorn-monitoring.labels" . | nindent 4 }}
{{- if $.Values.serviceMonitor.labels }}
    {{- toYaml $.Values.serviceMonitor.labels | nindent 4}}
{{- end }}
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: manager
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      interval: {{ $.Values.serviceMonitor.scrapeInterval }}
{{- end }}
