annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
# Please make sure that version and appVersion are always the same.
appVersion: 0.2.1
version: 0.2.1

description: A Library Helm Chart for grouping common logic between charts. This chart is not deployable by itself.
keywords:
  - common
  - helper
  - template
  - function
maintainers:
  - name: Andru Cherny
    url: https://github.com/wirwolf
name: someblackmagic-common
sources:
  - https://github.com/bitnami/charts
  - https://www.bitnami.com/
type: library
